# Generated by Django 4.2.11 on 2024-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_booking_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
